language: python
sudo: required

python:
  - "3.5"

#virtualenv:
#      system_site_packages: true

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt551 -y
  - sudo apt-get update
  - sudo apt-get install qt-latest
  - source /opt/qt55/bin/qt55-env.sh

install:
  - "pip install markdown whoosh"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: python test.py
